### ISSUE TITLE
Behaviour on hard power loss

### ISSUE THREAD

**Issue by nickbe** [tf198/phpqueues#1]
Hey there :)

I'm using this for quite some time now. And I'm really grateful for this project.
So, thanks!!!

I asked myself what would happen on power loss? Can the worker revognize that the last job hasn't finished yet?

And what about the multithread script in the root folder? How can I use this?

**Comment by tf198** [comment]
Hi Nick - great to hear someone is actually still using this!

In theory the FIFO itself is should be resilient to crash, every enqueue/dequeue is actioned by one atomic `fwrite` so a crash during one of those events should not corrupt the data.  In practice the OS/filesystem you are running this on comes into play but on modern filesystems it should be very unlikely...

That said, as I was reminding myself of the code I spotted a potential for corruption if it crashed during enqueue which I've fixed :-)

In terms of workers, once they dequeue the job it is gone from the queue - there is no mechanism for them to report success / failure to the queue.  To protect against crash or failure for any other reason I'd suggest something along the following lines:
- Immediately after dequeuing a job, write it to a `processing/<pid>.job` file.
- Do the work
- Once complete, delete the file

Then in your startup code you can scan your `processing` folder and re-enqueue any jobs it finds that dont have a process.  Make sure you do this **before** you start processing any more jobs otherwise you might get duplicated jobs.  There are a couple of PHP task queue libraries around which might be more suitable for this type of workload but most require an SQL backend.

Have created a wiki page to explain the basic usage of the [MultiProcess module](https://github.com/tf198/phpqueues/wiki/MultiProcess).  To be honest it was more an experiment into how far I could push PHP but I did use it for a few years to process large concurrent workloads before I moved away from PHP.

**Comment by nickbe** [comment]
Hey Tris :)

I'll implement the processing/<pid>.job - that should be pretty straightforward. Also for the wiki entry. That sounds like it's still pretty stable and so I'll try that right away.

Thanks for explaining and your effort. And :) of course the recent fix!
The solution is simple and quite elegant and I'm really happy I stumbled upon it in the first place.

Cheers
Nick
